
project_id = "ktpxqjyfguxckdzlqwai"

[auth]
enabled = true
schema = "auth"
secret = "your-secret-key"

[db]
password = "your-password"
port = 5432
host = "localhost"
user = "postgres"

[functions.send-email]
verify_jwt = false
