// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktpxqjyfguxckdzlqwai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cHhxanlmZ3V4Y2tkemxxd2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTc0NzQsImV4cCI6MjA2Njc3MzQ3NH0.2l0CozQum4g__SgD7CUz56k29D9Dh6tM8eVCn-3CWVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);